
package ru.otus.sua.L10.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Estimator", targetNamespace = "http://L10.sua.otus.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Estimator {


    /**
     * 
     * @param estimatingData
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://L10.sua.otus.ru/Estimator/estimateIncomeTaxRequest", output = "http://L10.sua.otus.ru/Estimator/estimateIncomeTaxResponse")
    public double estimateIncomeTax(
        @WebParam(name = "EstimatingData", partName = "EstimatingData")
        TaxData estimatingData);

}
