
package ru.otus.sua.L10.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstimateIncomeTaxService", targetNamespace = "http://L10.sua.otus.ru/", wsdlLocation = "http://localhost:8080/L10/EstimateIncomeTaxService?WSDL")
public class EstimateIncomeTaxService
    extends Service
{

    private final static URL ESTIMATEINCOMETAXSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTIMATEINCOMETAXSERVICE_EXCEPTION;
    private final static QName ESTIMATEINCOMETAXSERVICE_QNAME = new QName("http://L10.sua.otus.ru/", "EstimateIncomeTaxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/L10/EstimateIncomeTaxService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTIMATEINCOMETAXSERVICE_WSDL_LOCATION = url;
        ESTIMATEINCOMETAXSERVICE_EXCEPTION = e;
    }

    public EstimateIncomeTaxService() {
        super(__getWsdlLocation(), ESTIMATEINCOMETAXSERVICE_QNAME);
    }

    public EstimateIncomeTaxService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTIMATEINCOMETAXSERVICE_QNAME, features);
    }

    public EstimateIncomeTaxService(URL wsdlLocation) {
        super(wsdlLocation, ESTIMATEINCOMETAXSERVICE_QNAME);
    }

    public EstimateIncomeTaxService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTIMATEINCOMETAXSERVICE_QNAME, features);
    }

    public EstimateIncomeTaxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstimateIncomeTaxService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Estimator
     */
    @WebEndpoint(name = "EstimateIncomeTaxPort")
    public Estimator getEstimateIncomeTaxPort() {
        return super.getPort(new QName("http://L10.sua.otus.ru/", "EstimateIncomeTaxPort"), Estimator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Estimator
     */
    @WebEndpoint(name = "EstimateIncomeTaxPort")
    public Estimator getEstimateIncomeTaxPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://L10.sua.otus.ru/", "EstimateIncomeTaxPort"), Estimator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTIMATEINCOMETAXSERVICE_EXCEPTION!= null) {
            throw ESTIMATEINCOMETAXSERVICE_EXCEPTION;
        }
        return ESTIMATEINCOMETAXSERVICE_WSDL_LOCATION;
    }

}
